'use strict';

module.exports = [
  { name: 'acl',         method: 'acl' },
  { name: 'bind',        method: 'bind' },
  { name: 'checkout',    method: 'checkout' },
  { name: 'connect',     method: 'connect' },
  { name: 'copy',        method: 'copy' },
  { name: 'del',         method: 'delete' },
  { name: 'get',         method: 'get' },
  { name: 'head',        method: 'head' },
  { name: 'link',        method: 'link' },
  { name: 'lock',        method: 'lock' },
  { name: 'mSearch',     method: 'm-search' },
  { name: 'merge',       method: 'merge' },
  { name: 'mkactivity',  method: 'mkactivity' },
  { name: 'mkcalendar',  method: 'mkcalendar' },
  { name: 'mkcol',       method: 'mkcol' },
  { name: 'move',        method: 'move' },
  { name: 'notify',      method: 'notify' },
  { name: 'options',     method: 'options' },
  { name: 'patch',       method: 'patch' },
  { name: 'post',        method: 'post' },
  { name: 'propfind',    method: 'propfind' },
  { name: 'proppatch',   method: 'proppatch' },
  { name: 'purge',       method: 'purge' },
  { name: 'put',         method: 'put' },
  { name: 'rebind',      method: 'rebind' },
  { name: 'report',      method: 'report' },
  { name: 'search',      method: 'search' },
  { name: 'subscribe',   method: 'subscribe' },
  { name: 'trace',       method: 'trace' },
  { name: 'unbind',      method: 'unbind' },
  { name: 'unlink',      method: 'unlink' },
  { name: 'unlock',      method: 'unlock' },
  { name: 'unsubscribe', method: 'unsubscribe' }
];
